### ISSUE TITLE
`on-modify.timewarrior` adds spurious tags

### ISSUE THREAD

**Issue by dkasak** [GothenburgBitFactory/task-timewarrior-hook#20]
The `on-modify.timewarrior` hook creates spurious tags:

```
❯ task add "Test task"
Created task 118.

❯ task 118 modify +foo +bar
Modifying task 118 'Test task'.
Modified 1 task.

❯ task 118 start
Starting task fb3270e0 'Test task'.
Started 1 task.
Note: '"Test task"' is a new tag.
Tracking , "Test task" a b f o r
  Started 2023-04-26T03:48:40
  Current                  40
  Total               0:00:00
```

Note the tags `a`, `b`, `f`, `o`, `r`.

This appears to happen because the JSON object passed to the hook sometimes
contains a list for the `tags`, but other times it's a comma-separated list.
Placing some `print` calls shows the hook sees this for the above task:

```json
{
  "description": "Test task",
  "entry": "20230426T014808Z",
  "modified": "20230426T014829Z",
  "size": "small",
  "status": "pending",
  "uuid": "fb3270e0-06a5-4b3a-b272-59b2a1f32554",
  "tags": "bar,foo",
  "start": "20230426T014840Z"
}
```

**Comment by Smith4545** [comment]
@dkasak  If you use taskpirate or anything related to tasklib, take a look into this issue

https://github.com/tbabej/taskpirate/issues/19

**Comment by dkasak** [comment]
@Smith4545 Thank you for that reference. It's indeed what's causing my problem :(
